package main

import (
	"fmt"
	"sync"
	"sync/atomic"
	"time"
)

// Pac-man hardware specifics

const (
	// crystal oscillator
	crystalFreq = 18_432_000

	// divided into 3 phases
	clockDivisor = 3

	// to give master clock
	clockFreq = crystalFreq / clockDivisor

	// Horizontal dot counter runs from 128..511 (i.e. 384 counts),
	// clocked by the divided clock, giving a 16kHz line frequency.
	//
	// Note: only 288 hCounts are used for visible output, with
	// HBLANK asserted for the other 96 lines.
	hCounterMin = 128
	hCounterMax = 511
	hTotal      = (hCounterMax + 1 - hCounterMin)

	// Vertical dot counter runs from 248..511 (i.e. 264 counts),
	// clocked by HSYNC, giving a 60.6Hz frame frequency.
	vCounterMin = 248
	vCounterMax = 511
	vTotal      = (vCounterMax + 1 - vCounterMin)

	// Note: only 224 vCounts are used for visible output, with VBLANK
	// asserted for the other 40 lines.
	//
	// VBLANK is generated by latching ^(128V & 64V & 32V) on every 16V positive edge,
	// i.e. for period V%256 in [224..255] - that is V=248..255 and V=480..511, i.e. 40 lines,
	// So visible lines are in the range V=256..479 = 224 lines.
	//
	//   128V ________--------
	//    64V ____----____----
	//    32V __--__--__--__--
	//      D --------------__
	//    16V _-_-_-_-_-_-_-_-
	// VBLANK --------------__
	//
	vBlankPeriod = time.Second * (hTotal * vTotal) / clockFreq
)

// While IrqEnable register is clear, ^IRQ remains HIGH.
// When IrqEnable register is set, ^IRQ remains HIGH until VBLANK clocks in a 0, and ^IRQ goes low.

func startVblankTicker() {
	// Note watchdog RESET triggers after 16 VBLANK if not cleared.
	var vblankTicker = time.NewTicker(vBlankPeriod)

	go func() {
		for range vblankTicker.C {
			fmt.Println("VBLANK!")
			if optionsRegister[OptionIrqEnable].Load() {
				dataBus.Store(irqLowRegister.Load())
				irqAssertPin.Store(true)
			}
			if watchDogRegister.Load() == 0 {
				fmt.Println("WATCHDOG TIMEOUT!")
				resetAssertPin.Store(true)
			}
			watchDogRegister.Add(0xffffffff) // -1
		}
	}()
}

var (
	programROM    [0x4000]uint8
	tileRAM       [0x400]uint8 // videoMutex controls access
	paletteRAM    [0x400]uint8 // videoMutex controls access
	programRAM    [0x3f0]uint8
	spriteLookRAM [0x010]uint8 // videoMutex controls access

	audioMutex           sync.Mutex
	audioAccWaveRegister [16]uint8 // values in [0..15]; audioMutex controls access
	audioFreqVolRegister [16]uint8 // values in [0..15]; audioMutex controls access

	videoMutex        sync.Mutex
	spritePosRegister [16]uint8 // videoMutex controls access

	watchDogRegister atomic.Uint32 // countdown from 15..0
	irqLowRegister   atomic.Uint32 // lower 8 bits only
)

const (
	In0_NotJoystickUp uint8 = 1 << iota
	In0_NotJoystickLeft
	In0_NotJoystickRight
	In0_NotJoystickDown
	In0_NotRackAdvance  // (go to next level)
	In0_RisingCoinSlot1 // trigger by going from 0 to 1
	In0_RisingCoinSlot2 // trigger by going from 0 to 1
	In0_NotCreditButton
)

var (
	in0_State atomic.Uint32 // low 8 bits only
)

const (
	In1_NotJoystickUp uint8 = 1 << iota
	In1_NotJoystickLeft
	In1_NotJoystickRight
	In1_NotJoystickDown
	In1_NotBoardTest
	In1_NotP1Start
	In1_NotP2Start
	In1_NotCocktailMode
)

var (
	in1_State atomic.Uint32 // low 8 bits only
)

const (
	DipCoins0 uint8 = 1 << iota
	DipCoins1
	DipLives0
	DipLives1
	DipBonus2
	DipBonus1
	DipDifficulty
	DipGhostNames
)

var (
	dipSwitchState atomic.Uint32 // low 8 bits only
)

const (
	OptionIrqEnable      = iota // 1 enable, 0 disable
	OptionSoundEnable           // 1 enable, 0 disable
	OptionAuxBoardEnable        // not connected
	OptionFlipScreen            // 0 normal, 1 flipped for cocktail
	OptionPlayer1Lamp           //
	OptionPlayer2Lamp           //
	OptionCoinLockout           //
	OptionCoinCounter           //
)

var (
	optionsRegister [8]atomic.Bool
)

func ioInit() {
	in0_State.Store(uint32(0 |
		In0_NotJoystickUp |
		In0_NotJoystickLeft |
		In0_NotJoystickRight |
		In0_NotJoystickDown |
		In0_NotRackAdvance |
		In0_RisingCoinSlot1 |
		In0_RisingCoinSlot2 |
		In0_NotCreditButton))

	in1_State.Store(uint32(0 |
		In1_NotJoystickUp |
		In1_NotJoystickLeft |
		In1_NotJoystickRight |
		In1_NotJoystickDown |
		In1_NotBoardTest |
		In1_NotP1Start |
		In1_NotP2Start |
		In1_NotCocktailMode))
}

func ioWrite() {
	irqLowRegister.Store(dataBus.Load())
}

// ROM appears at 0x0000..0x3fff
// RAM appears at 0x4000..0x4fff and again from 0x6000
// I/O appears at 0x5000..0x5fff and again from 0x7000, and it repeats every 0x0100 within this regions.
// Entire memory maps repeats again from 0x8000.

// Note program RAM at 0x4ff0..0x4fff is read directly by the video
// hardware to get the sprite number and x/y flip bits. This is
// controlled by the U6,U5,U4 muxes in the sync bus controller.

func memRead(addr uint16) uint8 {
	// bit15 is ignored, so entire memory map repeats at 0x8000
	addr &^= 0x8000

	switch addr & 0x4000 {
	case 0x0000:
		// 0000..3fff - ROM
		return programROM[addr]

	case 0x4000:
		// 4000..5fff - RAM and I/O; notice bit 13 not used, hence the repeat at 0x6000
		switch addr & 0x1000 {
		case 0x0000:
			// 4000..4fff - RAM
			switch addr & 0x0c00 {
			case 0x0000:
				// 4000..43ff - Tile RAM
				return tileRAM[addr&0x3ff]
			case 0x0400:
				// 4400..47ff - Palette RAM
				return paletteRAM[addr&0x3ff]
			case 0x0800:
				// 4800..4bff - RAM absent
				return 0
			case 0x0c00:
				if addr&0x3f0 != 0x3f0 {
					// 4c00..4fef - Program RAM
					return programRAM[addr&0x3ff]
				} else {
					return spriteLookRAM[addr&0xf]
				}
			}

		case 0x1000:
			// 5000..5fff - I/O; notice bits 11..8 not used, hence repeat every 0x0100
			switch addr & 0x00c0 {
			case 0x0000:
				// 5000..503f - IN0
				v := uint8(in0_State.Load())
				return v

			case 0x0040:
				// 5040..507f - IN1
				v := uint8(in1_State.Load())
				return v

			case 0x0080:
				// 5080..50bf - DIPs
				v := uint8(dipSwitchState.Load())
				return v

			case 0x00c0:
				// 50c0..50ff - unused
				return 0
			}
		}
	}

	return 0
}

func memWrite(addr uint16, data uint8) {
	addr &^= 0x8000

	switch addr & 0x4000 {
	case 0x0000:
		// 0000..3fff - ROM
	case 0x4000:
		// 4000..5fff - RAM and I/O
		switch addr & 0x1000 {
		case 0x0000:
			// 4000..4fff - RAM
			switch addr & 0x0c00 {
			case 0x0000:
				// 4000.43ff - Tile RAM
				videoMutex.Lock()
				tileRAM[addr&0x3ff] = data
				videoMutex.Unlock()
			case 0x0400:
				// 4400..47ff - Palette RAM
				videoMutex.Lock()
				paletteRAM[addr&0x3ff] = data
				videoMutex.Unlock()
			case 0x0800:
				// 4800..4bff - no RAM
			case 0x0c00:
				if addr&0x3f0 != 0x3f0 {
					// 4c00..4fef - Program RAM
					programRAM[addr&0x3ff] = data
				} else {
					videoMutex.Lock()
					spriteLookRAM[addr&0xf] = data
					videoMutex.Unlock()
				}
			}

		case 0x1000:
			// 5000..5fff - I/O
			switch addr & 0x00c0 {
			case 0x0000:
				// 5000..503f - options
				optionsRegister[addr&0x07].Store((data & 1) == 1)

			case 0x0040:
				// 5040..507f - audio/video
				switch addr & 0x30 {
				case 0x00:
					//5040..504f - audio accumulators and waveforms
					audioMutex.Lock()
					audioAccWaveRegister[addr&0x0f] = data & 0x0f
					audioMutex.Unlock()
				case 0x10:
					//5050..505f - audio frequencies and volumes
					audioMutex.Lock()
					audioFreqVolRegister[addr&0x0f] = data & 0x0f
					audioMutex.Unlock()
				case 0x20:
					//5060..506f - sprite positions
					videoMutex.Lock()
					spritePosRegister[addr&0xf] = data
					videoMutex.Unlock()
				case 0x30:
					//5070..507f - unused
				}

			case 0x0080:
				// 5080..50bf - unused

			case 0x00c0:
				// 50c0..50ff - watchdog; any write resets it
				watchDogRegister.Store(15)
			}
		}
	}
}
