package main

import (
	"fmt"
	"os"
	"sync/atomic"
	"time"

	"github.com/adrmcintyre/z80/audio"
	"github.com/adrmcintyre/z80/video"
	"github.com/hajimehoshi/ebiten/v2"
)

// Pac-man hardware specifics

const (
	// crystal oscillator
	crystalFreq = 18_432_000

	// divided into 3 phases
	clockDivisor = 3

	// to give master clock
	clockFreq = crystalFreq / clockDivisor

	// Horizontal dot counter runs from 128..511 (i.e. 384 counts),
	// clocked by the divided clock, giving a 16kHz line frequency.
	//
	// Note: only 288 hCounts are used for visible output, with
	// HBLANK asserted for the other 96 lines.
	hCounterMin = 128
	hCounterMax = 511
	hTotal      = (hCounterMax + 1 - hCounterMin)

	// Vertical dot counter runs from 248..511 (i.e. 264 counts),
	// clocked by HSYNC, giving a 60.6Hz frame frequency.
	vCounterMin = 248
	vCounterMax = 511
	vTotal      = (vCounterMax + 1 - vCounterMin)

	// Note: only 224 vCounts are used for visible output, with VBLANK
	// asserted for the other 40 lines.
	//
	// VBLANK is generated by latching ^(128V & 64V & 32V) on every 16V positive edge,
	// i.e. for period V%256 in [224..255] - that is V=248..255 and V=480..511, i.e. 40 lines,
	// So visible lines are in the range V=256..479 = 224 lines.
	//
	//   128V ________--------
	//    64V ____----____----
	//    32V __--__--__--__--
	//      D --------------__
	//    16V _-_-_-_-_-_-_-_-
	// VBLANK --------------__
	//
	vBlankPeriod = time.Second * (hTotal * vTotal) / clockFreq
)

// Bits in in0 bank
const (
	In0_NotUp uint8 = 1 << iota
	In0_NotLeft
	In0_NotRight
	In0_NotDown
	In0_NotRackTest // (go to next level)
	In0_RisingCoin1 // trigger by going from 0 to 1
	In0_RisingCoin2 // trigger by going from 0 to 1
	In0_NotCredit
)

// Bits in in1 bank
const (
	In1_NotUp uint8 = 1 << iota
	In1_NotLeft
	In1_NotRight
	In1_NotDown
	In1_NotTest
	In1_NotStart1
	In1_NotStart2
	In1_NotCocktailMode
)

// Bits in dipswitch bank
const (
	// 00=2 coins, 1 play; 01=1 coin, 2 plays; 10=1 coin, 1 play; 11=free play
	DipCoins0 uint8 = 1 << iota
	DipCoins1

	// lives: 00=1 life, 01=2 lives, 10=3 lives, 11=5 lives
	DipLives0
	DipLives1

	// extra life at 00=10,000, 01=15,000, 10=20,000, 11=none
	DipBonus0
	DipBonus1

	LinkDifficulty // normal / hard (shorter blue/return times)
	LinkGhostNames // normal / alternative ghost names
)

// Options the software can write to control the hardware.
const (
	OptionIrqEnable      = iota // 1 enable, 0 disable
	OptionSoundEnable           // 1 enable, 0 disable
	OptionAuxBoardEnable        // not connected
	OptionFlipScreen            // 0 normal, 1 flipped for cocktail
	OptionPlayer1Lamp           //
	OptionPlayer2Lamp           //
	OptionCoinLockout           //
	OptionCoinCounter           //
)

var (
	programROM [0x4000]uint8
	programRAM [0x400]uint8

	watchdogRegister  atomic.Uint32 // counts down from 15..0 (using top 4 bits)
	irqLowRegister    atomic.Uint32 // lower 8 bits only
	irqEnableRegister atomic.Bool
	in0_State         atomic.Uint32 // low 8 bits only
	in1_State         atomic.Uint32 // low 8 bits only
	dipSwitchState    atomic.Uint32 // low 8 bits only
)

// While IrqEnable register is clear, ^IRQ remains HIGH.
// When IrqEnable register is set, ^IRQ remains HIGH until VBLANK clocks in a 0, and ^IRQ goes low.
func startVblankTicker() {
	// Note watchdog RESET triggers after 16 VBLANK if not cleared.
	var vblankTicker = time.NewTicker(vBlankPeriod)

	go func() {
		for range vblankTicker.C {
			if irqEnableRegister.Load() {
				dataBus.Store(irqLowRegister.Load())
				irqAssertPin.Store(true)
			}
			if !*flagNoWatchdog {
				if watchdogRegister.Load() == 0 {
					fmt.Println("WATCHDOG!")
					resetAssertPin.Store(true)
				}
			}
			watchdogRegister.Add(15 << 28) // subtract 1 from top 4 bits
		}
	}()
}

func writeOption(addr int, value bool) {
	switch addr {
	case OptionIrqEnable:
		irqEnableRegister.Store(value)
	case OptionSoundEnable:
		audio.SetSoundEnable(value)
	case OptionAuxBoardEnable:
		// do nothing
	case OptionFlipScreen:
		video.SetFlipScreen(value)
	case OptionPlayer1Lamp:
		video.SetPlayer1Lamp(value)
	case OptionPlayer2Lamp:
		video.SetPlayer2Lamp(value)
	case OptionCoinLockout:
		// do nothing
	case OptionCoinCounter:
		// do nothing
	}
}

func ioParseFlags() {
	switch *flagCoins {
	case 0, 1, 2, 3:
	default:
		fmt.Printf("illegal -dip-coins")
		os.Exit(1)
	}
	switch *flagLives {
	case 1, 2, 3, 5:
	default:
		fmt.Printf("illegal -dip-lives")
		os.Exit(1)
	}
	switch *flagBonus {
	case 0, 10_000, 15_000, 20_000:
	default:
		fmt.Printf("illegal -dip-bonus")
		os.Exit(1)
	}
}

func ioInit() {
	dipsUpdate()
	inputsUpdate()
}

type mapOfBits map[uint8]bool

func (mob mapOfBits) Uint32() (v uint32) {
	for i, bit := range mob {
		if bit {
			v |= uint32(i)
		}
	}
	return v
}

func dipsUpdate() {
	dips := mapOfBits{
		DipCoins0:      *flagCoins == 1 || *flagCoins == 2,
		DipCoins1:      *flagCoins == 2 || *flagCoins == 3,
		DipLives0:      *flagLives == 2 || *flagLives == 5,
		DipLives1:      *flagLives == 3 || *flagLives == 5,
		DipBonus0:      *flagBonus == 0 || *flagBonus == 15_000,
		DipBonus1:      *flagBonus == 0 || *flagBonus == 20_000,
		LinkDifficulty: !*flagDifficult,
		LinkGhostNames: !*flagAltGhosts,
	}.Uint32()
	dipSwitchState.Store(dips)
}

func inputsUpdate() {
	in0 := mapOfBits{
		In0_NotUp:       !ebiten.IsKeyPressed(ebiten.KeyUp),
		In0_NotLeft:     !ebiten.IsKeyPressed(ebiten.KeyLeft),
		In0_NotRight:    !ebiten.IsKeyPressed(ebiten.KeyRight),
		In0_NotDown:     !ebiten.IsKeyPressed(ebiten.KeyDown),
		In0_NotRackTest: !*flagRackTest,
		In0_RisingCoin1: !false,
		In0_RisingCoin2: !false,
		In0_NotCredit:   !ebiten.IsKeyPressed(ebiten.KeyC),
	}.Uint32()

	// use same arrow keys for both players
	in1 := mapOfBits{
		In1_NotUp:           !ebiten.IsKeyPressed(ebiten.KeyUp),
		In1_NotLeft:         !ebiten.IsKeyPressed(ebiten.KeyLeft),
		In1_NotRight:        !ebiten.IsKeyPressed(ebiten.KeyRight),
		In1_NotDown:         !ebiten.IsKeyPressed(ebiten.KeyDown),
		In1_NotTest:         (!*flagTest) != ebiten.IsKeyPressed(ebiten.KeyT),
		In1_NotStart1:       !ebiten.IsKeyPressed(ebiten.Key1),
		In1_NotStart2:       !ebiten.IsKeyPressed(ebiten.Key2),
		In1_NotCocktailMode: !*flagCocktail,
	}.Uint32()

	in0_State.Store(in0)
	in1_State.Store(in1)
}

func ioWrite() {
	irqLowRegister.Store(dataBus.Load())
}

// ROM appears at 0x0000..0x3fff
// RAM appears at 0x4000..0x4fff and again from 0x6000
// I/O appears at 0x5000..0x5fff and again from 0x7000, and it repeats every 0x0100 within this regions.
// Entire memory maps repeats again from 0x8000.

// Note program RAM at 0x4ff0..0x4fff is read directly by the video
// hardware to get the sprite number and x/y flip bits. This is
// controlled by the U6,U5,U4 muxes in the sync bus controller.

func busRead(addr uint16) uint8 {
	var v uint8

	// bit15 is ignored, so entire memory map repeats at 0x8000
	addr &^= 0x8000

	switch addr & 0x4000 {
	case 0x0000:
		// 0000..3fff - ROM
		// early exit to skip memory tracing for ROM
		return programROM[addr]

	case 0x4000:
		// 4000..5fff - RAM and I/O; notice bit 13 not used, hence the repeat at 0x6000
		switch addr & 0x1000 {
		case 0x0000:
			// 4000..4fff - RAM
			switch addr & 0x0c00 {
			case 0x0000:
				// 4000..43ff - Tile RAM
				v = uint8(video.TileRAM[addr&0x3ff])
			case 0x0400:
				// 4400..47ff - Palette RAM
				v = uint8(video.PalRAM[addr&0x3ff])
			case 0x0800:
				// 4800..4bff - RAM absent
				v = 0
			case 0x0c00:
				// 4c00..4fef - Program RAM
				v = programRAM[addr&0x3ff]
			}

		case 0x1000:
			// 5000..5fff - I/O; notice bits 11..8 not used, hence repeat every 0x0100
			switch addr & 0x00c0 {
			case 0x0000:
				// 5000..503f - IN0
				v = uint8(in0_State.Load())

			case 0x0040:
				// 5040..507f - IN1
				v = uint8(in1_State.Load())

			case 0x0080:
				// 5080..50bf - DIPs
				v = uint8(dipSwitchState.Load())

			case 0x00c0:
				// 50c0..50ff - unused
				v = 0
			}
		}
	}

	if traceMem[addr] {
		fmt.Printf("%04x READ %02x\n", addr, v)
	}

	return v
}

func busWrite(addr uint16, data uint8) {
	addr &^= 0x8000

	if traceMem[addr] {
		fmt.Printf("%04x WRITE %02x\n", addr, data)
	}

	switch addr & 0x4000 {
	case 0x0000:
		// 0000..3fff - ROM
	case 0x4000:
		// 4000..5fff - RAM and I/O
		switch addr & 0x1000 {
		case 0x0000:
			// 4000..4fff - RAM
			switch addr & 0x0c00 {
			case 0x0000:
				// 4000.43ff - Tile RAM
				video.Mutex.Lock()
				video.TileRAM[addr&0x3ff] = video.Tile(data)
				video.Mutex.Unlock()
			case 0x0400:
				// 4400..47ff - Palette RAM
				video.Mutex.Lock()
				video.PalRAM[addr&0x3ff] = video.Palette(data)
				video.Mutex.Unlock()
			case 0x0800:
				// 4800..4bff - no RAM
			case 0x0c00:
				// 4c00..4fef - Program RAM
				programRAM[addr&0x3ff] = data
				if addr&0x3f0 == 0x3f0 {
					// 4ff0..4fff - Sprite look RAM
					video.Mutex.Lock()
					video.SpriteLookRAM[addr&0xf] = data
					video.Mutex.Unlock()
				}
			}

		case 0x1000:
			// 5000..5fff - I/O
			switch addr & 0x00c0 {
			case 0x0000:
				// 5000..503f - options
				writeOption(int(addr&0x07), (data&1) == 1)

			case 0x0040:
				// 5040..507f - audio/video
				switch addr & 0x30 {
				case 0x00:
					//5040..504f - audio accumulators and waveforms
					audio.AccWaveWrite(addr&0x0f, data&0x0f)
				case 0x10:
					//5050..505f - audio frequencies and volumes
					audio.FreqVolWrite(addr&0x0f, data&0x0f)
				case 0x20:
					//5060..506f - sprite positions
					video.Mutex.Lock()
					video.SpritePosRegister[addr&0xf] = data
					video.Mutex.Unlock()
				case 0x30:
					//5070..507f - unused
				}

			case 0x0080:
				// 5080..50bf - unused

			case 0x00c0:
				// 50c0..50ff - watchdog; any write resets it
				watchdogRegister.Store(15 << 28)
			}
		}
	}
}
