package main

import (
	"time"

	"github.com/adrmcintyre/z80pacman/audio"
	"github.com/adrmcintyre/z80pacman/z80"
)

const (
	// crystal oscillator
	crystalFreq = 18_432_000

	// divided into 3 phases
	clockDivisor = 3

	// to give master clock
	clockFreq = crystalFreq / clockDivisor

	// Horizontal dot counter runs from 128..511 (i.e. 384 counts),
	// clocked by the divided clock, giving a 16kHz line frequency.
	//
	// Note: only 288 hCounts are used for visible output, with
	// HBLANK asserted for the other 96 lines.
	hCounterMin = 128
	hCounterMax = 511
	hTotal      = (hCounterMax + 1 - hCounterMin)

	// Vertical dot counter runs from 248..511 (i.e. 264 counts),
	// clocked by HSYNC, giving a 60.6Hz frame frequency.
	vCounterMin = 248
	vCounterMax = 511
	vTotal      = (vCounterMax + 1 - vCounterMin)

	// Note: only 224 vCounts are used for visible output, with VBLANK
	// asserted for the other 40 lines.
	//
	// VBLANK is generated by latching ^(128V & 64V & 32V) on every 16V positive edge,
	// i.e. for period V%256 in [224..255] - that is V=248..255 and V=480..511, i.e. 40 lines,
	// So visible lines are in the range V=256..479 = 224 lines.
	//
	//   128V ________--------
	//    64V ____----____----
	//    32V __--__--__--__--
	//      D --------------__
	//    16V _-_-_-_-_-_-_-_-
	// VBLANK --------------__
	//
	vBlankPeriod = time.Second * (hTotal * vTotal) / clockFreq
)

// While IrqEnable register is clear, ^IRQ remains HIGH.
// When IrqEnable register is set, ^IRQ remains HIGH until VBLANK clocks in a 0, and ^IRQ goes low.
func vblankStart() {
	var vblankTicker = time.NewTicker(vBlankPeriod)

	go func() {
		for range vblankTicker.C {
			audio.Tick()
			if irqEnableRegister.Load() {
				z80.DataBus.Store(irqLowRegister.Load())
				z80.IrqAssertPin.Store(true)
			}
			watchdogTick()
		}
	}()
}
